# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vbguest.auto_update = false

  config.vm.define "bonus_host" do |machine|
    machine.vm.box = "boeboe/centos7-vbguest"
    machine.vm.synced_folder '../data', '/data'
    machine.vm.hostname = "bonus.host"
    machine.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vbguest.auto_update = false

  config.vm.define "tax_host" do |machine|
    machine.vm.box = "boeboe/centos7-vbguest"
    machine.vm.synced_folder '../data', '/data'
    machine.vm.hostname = "tax.host"
    machine.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end